main: com.aquanova_mp.winhomes.WinHomes
name: WinHomes
version: 0.1.0
author: Archer6621
description: WinDooM's very own home plugin
commands:
  home:
    description: Teleports the player to his home if set, or teleports to another's home if a player's name is given
    usage: /home <others_home>
  home_set:
    description: Sets your home
    usage: /home_set
    aliases: [sethome, homeset]
  home_invite:
    description: Invites a player to your home
    usage: /home_invite <player_name>
    aliases: [invitehome, homeinvite]
  home_uninvite:
    description: Uninvites a player from your home
    usage: /home_uninvite <player_name>
    aliases: [uninvitehome, homeuninvite]